image:
   registry: "localhost:32000"
   tag: "latest"
   pullPolicy: "Always"
   # registry: "gethue"
   # tag: "latest"
   # pullPolicy: "IfNotPresent"
website:
  enabled: true
  replicas: 1
  domain: "gethue.com"
docs:
  enabled: true
  replicas: 1
  domain: "docs.gethue.com"
monitoring:
  enabled: false
ingress:
  create: false
  hasAuth: false
  type: "nginx"
  # type: "nginx-ssl"
  email: "team@gethue.com"
