language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          python: pypy
        - os: linux
          python: pypy3
        # It's important to use 'macpython' builds to get the least
        # restrictive wheel tag. It's also important to avoid
        # 'homebrew 3' because it floats instead of being a specific version.
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 2.7'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.4'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.5'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.6.0'
        - services:
            - docker
          env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
          before_install:
            - if [[ $TRAVIS_TAG ]]; then bash .manylinux.sh; fi
            - exit 0
        - services:
            - docker
          env:
            - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
            - PRE_CMD=linux32
          before_install:
            - if [[ $TRAVIS_TAG ]]; then bash .manylinux.sh; fi
            - exit 0
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/MacPython/terryfy; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment $TERRYFY_PYTHON venv; fi
install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"
script:
    - coverage run setup.py test -q
notifications:
    email: false
after_success:
    - coveralls
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers = pypi                        >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo username=zope.wheelbuilder                  >> ~/.pypirc
    - echo password=$PYPIPASSWORD                      >> ~/.pypirc
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then pip install twine; fi
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_wheel; fi
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then twine upload dist/*; fi

env:
    global:
        secure: "CeOq8/6F8IlbRpKEk2z3RPD/q5cBCPXGOUgjYryG/c+7P6SCTxaTKfxiJPqT3sGgO8x/HcJVuvZghyqCPvysk3cbnq4SiMtI1S0hS/N3DFsGZHn25YQBipAYjA4YDUb6GqCpsSUIXdbGMEzG7DOSB6c+49+//wkjbBFHmPNWvMQ="

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
